((LAMBDA (XOR NTH HEADEQ LFSR DODOSKO)
  (DODOSKO (QUOTE (DODO SKO SKO SKO SKO SKO SKO SKO DODO))))
 (QUOTE (LAMBDA (X Y)
   (COND ((EQ X Y) (QUOTE SKO))
         ((QUOTE T) (QUOTE DODO)))))
 (QUOTE (LAMBDA (N L)
   (COND (N (NTH (CDR N) (CDR L)))
         ((QUOTE T) (CAR L)))))
 (QUOTE (LAMBDA (L H)
   (COND ((ATOM H) (QUOTE T))
         ((EQ (CAR L) (CAR H)) (HEADEQ (CDR L) (CDR H)))
         ((QUOTE T) NIL))))
 (QUOTE (LAMBDA (STATE)
   (CONS (XOR (NTH (QUOTE (I I I I I I I I)) STATE)
              (XOR (NTH (QUOTE (I I I I I I I)) STATE)
                   (XOR (NTH (QUOTE (I I I I)) STATE)
                        (NTH (QUOTE (I I I)) STATE))))
         STATE)))
 (QUOTE (LAMBDA (STATE)
   (CONS (CAR STATE)
         (COND ((HEADEQ STATE
                  (QUOTE (SKO SKO SKO DODO SKO SKO SKO DODO SKO SKO SKO DODO)))
                (QUOTE (LOVE CHU NYU HEART)))
               ((QUOTE T) (DODOSKO (LFSR STATE))))))))

